def brush_teeth():
				print("hhgjhghhgf")
				print("hhgjhghhgf")
				print("hhgjhghhgf")
				print("hhgjhghhgf")
				print("hhgjhghhgf")
				print("hhgjhghhgf")
				print("hhgjhghhgf")
				print("hhgjhghhgf")
brush_teeth()